CREATE TABLE [dbo].[VENTA]
(
[IDVENT] [int] NOT NULL IDENTITY(1, 1),
[FECVENT] [date] NULL,
[CODVEND] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CODCLI] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TIPVENT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [IDVENT_PK] PRIMARY KEY CLUSTERED ([IDVENT]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_CLIENTE] FOREIGN KEY ([CODCLI]) REFERENCES [dbo].[CLIENTE] ([CODCLI])
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_VENDEDOR] FOREIGN KEY ([CODVEND]) REFERENCES [dbo].[VENDEDOR] ([CODVEND])
GO
