CREATE TABLE [dbo].[PRODUCTO]
(
[CODPRO] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NOMPRO] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PREPRO] [decimal] (8, 2) NULL,
[STOCKPRO] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTO] ADD CONSTRAINT [CODPRO_PK] PRIMARY KEY CLUSTERED ([CODPRO]) ON [PRIMARY]
GO
