CREATE TABLE [dbo].[CLIENTE]
(
[CODCLI] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DNICLI] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NOMCLI] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[APECLI] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CELCLI] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMACLI] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FECNACCLI] [date] NULL,
[UBICLI] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENTE] ADD CONSTRAINT [CODCLI_PK] PRIMARY KEY CLUSTERED ([CODCLI]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENTE] ADD CONSTRAINT [CLIENTE_UBIGEO] FOREIGN KEY ([UBICLI]) REFERENCES [dbo].[UBIGEO] ([CODUBI])
GO
