CREATE TABLE [dbo].[VENDEDOR]
(
[CODVEND] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NOMVEND] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[APEVEND] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DNIVEND] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CELVEND] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOMVEND] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UBIVEND] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENDEDOR] ADD CONSTRAINT [CODVEND_PK] PRIMARY KEY CLUSTERED ([CODVEND]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENDEDOR] ADD CONSTRAINT [VENDEDOR_UBIGEO] FOREIGN KEY ([UBIVEND]) REFERENCES [dbo].[UBIGEO] ([CODUBI])
GO
