CREATE TABLE [dbo].[VENTA_DETALLE]
(
[IDVENTDET] [int] NOT NULL IDENTITY(1, 1),
[IDVENT] [int] NULL,
[CODPRO] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CANTVENTDET] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [IDVENTDET_PK] PRIMARY KEY CLUSTERED ([IDVENTDET]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [VENTA_DETALLE_PRODUCTO] FOREIGN KEY ([CODPRO]) REFERENCES [dbo].[PRODUCTO] ([CODPRO])
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [VENTA_DETALLE_VENTA] FOREIGN KEY ([IDVENT]) REFERENCES [dbo].[VENTA] ([IDVENT])
GO
